CREATE OR REPLACE FUNCTION IMPLODE(input varcahr2) RETURN VARCHAR2
PARALLEL ENABLE AGGREGATE USING IMPLODE_TYPE;

GRANT EXECUTE ON IMPLODE TO USER;

CREATE OR REPLACE FUNCTION IMPLODE_NL;
(
	x VARCHAR2
) RETURN VARCHAR2
PARALLEL ENABLE
AGGREGATE USING implode_nl;